In [1]:
from pandasgui import show
import pandas as pd

In [36]:
#df = pd.read_excel(r"F:\数据集\肖圆圆\一卡通补贴发放统计-查询到户-20250407094224.xlsx")
df = pd.read_csv(r"F:\数据集\肖圆圆\一卡通补贴发放统计表.csv",low_memory=False)

C:\Users\hnsj\AppData\Local\Temp\ipykernel_16016\4223771334.py:2: DtypeWarning:

Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.

In [17]:
df1 = pd.read_excel(r"F:\数据集\肖圆圆\一卡通补贴发放统计-查询到户-20250407094224.xlsx",sheet_name='Sheet1',header=None)

In [29]:
# 假设df1没有表头，使用数字列名(0,1,2,...)
# 将df1的列名设置为与df相同的列名
df1.columns = df.columns

# 现在可以正常合并
merged_df = pd.concat([df, df1], ignore_index=True)

In [35]:
# 导出CSV文件
merged_df.to_csv('F:\数据集\肖圆圆\一卡通补贴发放统计表.csv',encoding='utf-8-sig')

In [49]:
df =pd.read_excel(r"F:\数据集\ymy\2024年度救助资金资料\救助资金合并.xlsx")

In [51]:
df2 =pd.read_excel(r"F:\数据集\ymy\2024年度救助资金资料\疾控中心死亡人员名单.xlsx")

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16795 entries, 0 to 16794
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   数据文件来源       16795 non-null  object
 1   来源表          16795 non-null  object
 2   序号           16792 non-null  float64
 3   户主姓名         16793 non-null  object
 4   乡镇           10545 non-null  object
 5   村组名称         16610 non-null  object
 6   身份证号         16792 non-null  object
 7   家庭人口         16593 non-null  float64
 8   家庭类别         16594 non-null  object
 9   救助类别         16728 non-null  object
 10  发放金额(元)      16795 non-null  int64
 11  电话号码         16658 non-null  object
 12  一卡通帐号        5032 non-null   object
 13  乡（镇）         35 non-null     object
 14  村（社区）        34 non-null     object
 15  户主联系方式       50 non-null     float64
 16  受灾时间         118 non-null    object
 17  户籍人口数        35 non-null     float64
 18  家庭需救助人口（人数）  51 non-null     float64
 19  备注           65 non-null     object
 20  家庭地址         84 non-null     object
 21  联系电话         83 non-null     float64
 22  户籍 口         84 non-null     float64
 23  实际居住 口       84 non-null     float64
 24  救助原因         84 non-null     object
 25  所在村民小组村组     64 non-null     object
dtypes: float64(8), int64(1), object(17)
memory usage: 3.3+ MB

In [34]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1106847 entries, 0 to 1106846
Data columns (total 23 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   序号         1106847 non-null  int64
 1   补贴类型       1106847 non-null  object
 2   申报对象代码     927682 non-null   float64
 3   申报对象姓名     927682 non-null   object
 4   申报对象身份证号码  927682 non-null   object
 5   是否代领       927682 non-null   object
 6   收款对象代码     1106847 non-null  int64
 7   收款对象姓名     1106847 non-null  object
 8   收款身份证号码    1106847 non-null  object
 9   发放账号       1106847 non-null  object
 10  补贴数量       1106847 non-null  float64
 11  补贴标准       1106847 non-null  float64
 12  补贴金额构成     91960 non-null    object
 13  应发金额       1106847 non-null  float64
 14  实发金额       1106847 non-null  float64
 15  发放日期       1106847 non-null  object
 16  代发银行       1106847 non-null  object
 17  申报对象居住地址   923437 non-null   object
 18  申报对象手机号码   890990 non-null   float64
 19  政策单位       912964 non-null   object
 20  期数         577833 non-null   object
 21  批次         825601 non-null   float64
 22  备注         312478 non-null   object
dtypes: float64(7), int64(2), object(14)
memory usage: 194.2+ MB

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106847 entries, 0 to 106846
Data columns (total 23 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       106847 non-null  int64
 1   1       106847 non-null  object
 2   2       89855 non-null   float64
 3   3       89855 non-null   object
 4   4       89855 non-null   object
 5   5       89855 non-null   object
 6   6       106847 non-null  int64
 7   7       106847 non-null  object
 8   8       106847 non-null  object
 9   9       106847 non-null  int64
 10  10      106847 non-null  float64
 11  11      106847 non-null  float64
 12  12      7230 non-null    object
 13  13      106847 non-null  float64
 14  14      106847 non-null  float64
 15  15      106847 non-null  object
 16  16      106847 non-null  object
 17  17      89297 non-null   object
 18  18      86037 non-null   float64
 19  19      90252 non-null   object
 20  20      55504 non-null   object
 21  21      79518 non-null   float64
 22  22      32956 non-null   object
dtypes: float64(7), int64(3), object(13)
memory usage: 18.7+ MB

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106846 entries, 0 to 106845
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   1000001                     106846 non-null  int64
 1   01004201020160000-耕地地力保护补贴  106846 non-null  object
 2   430401023031016007          89854 non-null   float64
 3   全裕容                         89854 non-null   object
 4   430422195301051438          89854 non-null   object
 5   否                           89854 non-null   object
 6   430401023031016007.1        106846 non-null  int64
 7   全裕容.1                       106846 non-null  object
 8   430422195301051438.1        106846 non-null  object
 9   81011450012947352           106846 non-null  int64
 10  3.1                         106846 non-null  float64
 11  105                         106846 non-null  float64
 12  Unnamed: 12                 7230 non-null    object
 13  325.5                       106846 non-null  float64
 14  325.5.1                     106846 non-null  float64
 15  2024-10-17                  106846 non-null  object
 16  农村信用社                       106846 non-null  object
 17  泉湖镇源泉村上升组                   89296 non-null   object
 18  15570959742                 86036 non-null   float64
 19  农业农村局                       90251 non-null   object
 20  Unnamed: 20                 55504 non-null   object
 21  3                           79517 non-null   float64
 22  Unnamed: 22                 32956 non-null   object
dtypes: float64(7), int64(3), object(13)
memory usage: 18.7+ MB

In [6]:
df.head()

,序号,补贴类型,申报对象代码,申报对象姓名,申报对象身份证号码,是否代领,收款对象代码,收款对象姓名,收款身份证号码,发放账号,...,应发金额,实发金额,发放日期,代发银行,申报对象居住地址,申报对象手机号码,政策单位,期数,批次,备注
0,1,01004028020200000-稻谷目标价格补贴,4.304010e+17,刘华生,430422196307105614,否,430401002002001001,刘华生,430422196307105614,81011450009419586,...,252.00,252.00,2024-01-08,农村信用社,衡南县向阳桥街道黄河村排楼组,1.997475e+10,NaN,NaN,1.0,NaN
1,2,04007043030340000-义务教育家庭经济困难学生生活补助,4.304010e+17,刘宇铭,430422201611036012,是,430401002002001001,刘华生,430422196307105614,81011450009419586,...,312.50,312.50,2024-10-31,农村信用社,衡南县向阳桥街道水口社区第三居民小组,1.511684e+10,NaN,NaN,3.0,NaN
2,3,04007043030340000-义务教育家庭经济困难学生生活补助,4.304010e+17,刘梓涵,430422201802260164,是,430401002002001001,刘华生,430422196307105614,81011450009419586,...,625.00,625.00,2025-02-17,农村信用社,NaN,NaN,NaN,NaN,27.0,NaN
3,4,01004028020200000-稻谷目标价格补贴,4.304010e+17,刘华生,430422196307105614,否,430401002002001001,刘华生,430422196307105614,81011450009419586,...,252.00,252.00,2024-12-09,农村信用社,衡南县向阳桥街道黄河村排楼组,1.997475e+10,NaN,NaN,3.0,NaN
4,5,01004201020160000-耕地地力保护补贴,4.304010e+17,阳运汉,430422195305085619,否,430401002002001002,阳运汉,430422195305085619,81011450009419597,...,1103.55,1103.55,2024-10-17,农村信用社,衡南县向阳桥街道黄河村排楼组,1.509197e+10,农业农村局,NaN,3.0,NaN

In [38]:
df.tail()

,Unnamed: 0,序号,补贴类型,申报对象代码,申报对象姓名,申报对象身份证号码,是否代领,收款对象代码,收款对象姓名,收款身份证号码,...,应发金额,实发金额,发放日期,代发银行,申报对象居住地址,申报对象手机号码,政策单位,期数,批次,备注
1106842,1106842,1106843,05165-困难残疾人生活补贴,4.304010e+18,周子璇,430422200206039223,否,4304010190220162265,周子璇,430422200206039223,...,90.0,90.0,2024-12-25,农村信用社,三塘镇农科所社区镇残联,1.822927e+10,民政局,12月份,NaN,NaN
1106843,1106843,1106844,05165-困难残疾人生活补贴,4.304010e+18,张多媛,430422195003110049,否,4304010190220162266,张多媛,430422195003110049,...,90.0,90.0,2024-10-23,农村信用社,三塘镇农科所社区镇残联,1.821607e+10,民政局,10月份,NaN,NaN
1106844,1106844,1106845,05165-困难残疾人生活补贴,4.304010e+18,张多媛,430422195003110049,否,4304010190220162266,张多媛,430422195003110049,...,90.0,90.0,2024-12-02,农村信用社,三塘镇农科所社区镇残联,1.821607e+10,民政局,11月份,NaN,NaN
1106845,1106845,1106846,05165-困难残疾人生活补贴,4.304010e+18,张多媛,430422195003110049,否,4304010190220162266,张多媛,430422195003110049,...,90.0,90.0,2024-12-25,农村信用社,三塘镇农科所社区镇残联,1.821607e+10,民政局,12月份,NaN,NaN
1106846,1106846,1106847,05165-困难残疾人生活补贴,4.304010e+18,张多媛,430422195003110049,否,4304010190220162266,张多媛,430422195003110049,...,90.0,90.0,2024-09-23,农村信用社,三塘镇农科所社区镇残联,1.821607e+10,民政局,09月份,NaN,NaN

In [8]:
df.describe()

,序号,申报对象代码,收款对象代码,补贴数量,补贴标准,应发金额,实发金额,申报对象手机号码,批次
count,1000000.000000,8.378270e+05,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,8.049530e+05,746083.000000
mean,500000.500000,4.335347e+17,4.304010e+17,1.119202,42.446809,513.268757,513.268757,1.596505e+10,3.693700
std,288675.278933,1.108705e+17,6.234520e+09,2.350771,113.810434,1110.273286,1110.273286,2.570405e+09,3.911179
min,1.000000,4.304010e+14,4.304010e+17,0.000000,0.000000,0.400000,0.400000,7.348766e+09,1.000000
25%,250000.750000,4.304010e+17,4.304010e+17,0.000000,0.000000,90.000000,90.000000,1.387346e+10,1.000000
50%,500000.500000,4.304010e+17,4.304010e+17,1.000000,0.000000,286.500000,286.500000,1.557343e+10,3.000000
75%,750000.250000,4.304010e+17,4.304010e+17,1.000000,105.000000,585.000000,585.000000,1.821602e+10,3.000000
max,1000000.000000,4.304010e+18,4.304010e+17,388.400000,10000.000000,313500.000000,313500.000000,1.890748e+11,30.000000

In [9]:
df.columns

Index(['序号', '补贴类型', '申报对象代码', '申报对象姓名', '申报对象身份证号码', '是否代领', '收款对象代码',
       '收款对象姓名', '收款身份证号码', '发放账号', '补贴数量', '补贴标准', '补贴金额构成', '应发金额', '实发金额',
       '发放日期', '代发银行', '申报对象居住地址', '申报对象手机号码', '政策单位', '期数', '批次', '备注'],
      dtype='object')

In [40]:
import pandas as pd

# 假设df是你的DataFrame
# 如果还未读取数据，可以使用: df = pd.read_excel('your_file.xlsx')

# 按补贴类型分组并汇总
summary = df.groupby('补贴类型').agg({
    '补贴数量': 'sum',
    '应发金额': 'sum',
    '实发金额': 'sum'
}).reset_index()

# 显示汇总结果
print(summary)

# 可选：保存汇总结果到Excel
summary.to_excel('补贴类型汇总.xlsx', index=False)

                                    补贴类型       补贴数量         应发金额         实发金额
0             01004028020200000-稻谷目标价格补贴       0.00  27679984.00  27679984.00
1             01004201020160000-耕地地力保护补贴  815828.72  85662015.60  85662015.60
2         01004202020160000-耕地地力保护补贴（结余）   18271.32   3087853.08   3087853.08
3                             01107-棉花奖补    1738.27    347654.00    347654.00
4                02005134020770401-油茶林补助       0.00   2467045.00   2467045.00
..                                   ...        ...          ...          ...
88                         13122-一次性生活补助       0.00     12000.00     12000.00
89    14002009020110000-农村道路客运补贴（个体经营部分）       0.00   3015400.10   3015400.10
90    14002010020110000-农村水路客运补贴（个体经营部分）       0.00    162079.90    162079.90
91            15015097030580000-两癌妇女救助资金      13.00    130000.00    130000.00
92  16016098030590000-计划生育特殊家庭重病大病住院护理补贴    1021.00    102100.00    102100.00

[93 rows x 4 columns]

In [11]:
show(summary)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\hnsj\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [52]:
df2.columns

Index(['序号', '姓名', '性别', '身份证号码', '证件号码', '出生日期', '年龄', '民族', '婚姻状况', '个人身份',
       '文化程度', '死者生前常住地址类别', '死者生前详细地址', '生前常住村', '户籍详细地区', '户籍所在村', '户籍所在村编码',
       '死者生前工作单位/学校名称', '死亡日期', '死亡地点', '可联系的家属姓名', '家属联系电话', '家属联系地址或工作单位',
       'a直接导致死亡的疾病', 'a直接导致死亡的疾病ICD10编码', 'a发病到死亡的时间间隔', 'a发病到死亡的时间间隔单位',
       'b直接导致死亡的疾病', 'b直接导致死亡的疾病ICD10编码', 'b发病到死亡的时间间隔', 'b发病到死亡的时间间隔单位',
       '根本死亡原因', '根本死亡原因编码', '最高诊断单位', '最高诊断依据', '填卡医师', '住院号', '医生填卡日期', '备注',
       '死者生前病史及症状体征', '被调查者姓名', '与死者关系', '联系地址或工作单位', '被调查者电话号码', '死因推断',
       '调查者签名', '调查日期', '删除时间', '录入时间', '录入人ID', '审核标志', '一审时间', '审核时间',
       '卡片来源', '国家或地区', '报告人', '民警签名', '卡片状态编码', '卡片状态', '单位类型编码', '单位类型名称',
       '死者生前常住地址'],
      dtype='object')

In [53]:
df.columns

Index(['数据文件来源', '来源表', '序号', '户主姓名', '乡镇', '村组名称', '身份证号', '家庭人口', '家庭类别',
       '救助类别', '发放金额(元)', '电话号码', '一卡通帐号', '乡（镇）', '村（社区）', '户主联系方式', '受灾时间',
       '户籍人口数', '家庭需救助人口（人数）', '备注', '家庭地址', '联系电话', '户籍 口', '实际居住 口', '救助原因',
       '所在村民小组村组'],
      dtype='object')

In [55]:
show(df2)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [56]:
#df3 = pd.merge(df1, df2, on='A', how='left')
#除了 left 之外，pandas.merge() 函数的 how 参数还可以取以下值：

#'inner': 内连接，仅返回两个表中都存在的记录。
#'right': 右连接，返回右表中的所有记录，以及左表中连接键匹配的记录。
#'outer': 外连接，返回两个表中的所有记录，以及连接键匹配的记录。
df3 = pd.merge(df,df2, left_on='身份证号', right_on='证件号码', how='inner', indicator=True)
show(df3)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [57]:
df3.to_excel(r"F:\数据集\ymy\2024年度救助资金资料\救助与死亡人员查询.xlsx", index=False)

In [47]:
# 模糊查找姓名中包含"三"的所有行
result = df[df['收款身份证号码'].str.contains('430432195208068817', na=False)]
print(result)

Empty DataFrame
Columns: [Unnamed: 0, 序号, 补贴类型, 申报对象代码, 申报对象姓名, 申报对象身份证号码, 是否代领, 收款对象代码, 收款对象姓名, 收款身份证号码, 发放账号, 补贴数量, 补贴标准, 补贴金额构成, 应发金额, 实发金额, 发放日期, 代发银行, 申报对象居住地址, 申报对象手机号码, 政策单位, 期数, 批次, 备注]
Index: []

[0 rows x 24 columns]

In [48]:
# 模糊查找姓名中包含"三"的所有行
result2 = df[df['申报对象身份证号码'].str.contains('430432195208068817', na=False)]
print(result2)

Empty DataFrame
Columns: [Unnamed: 0, 序号, 补贴类型, 申报对象代码, 申报对象姓名, 申报对象身份证号码, 是否代领, 收款对象代码, 收款对象姓名, 收款身份证号码, 发放账号, 补贴数量, 补贴标准, 补贴金额构成, 应发金额, 实发金额, 发放日期, 代发银行, 申报对象居住地址, 申报对象手机号码, 政策单位, 期数, 批次, 备注]
Index: []

[0 rows x 24 columns]